In [1]:
# Show all Jupyter output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# import files from above
import sys
sys.path.append('..')

In [2]:
import pandas as pd
import numpy as np

In [3]:
rois_file = "../data/andrew/rois/frame00001.csv"
df = pd.read_csv(rois_file)
rois = df.values
rois
rois = rois[1:, :]
rois

array([[  0,   0,   0, 539, 959],
       [  1, 237, 176, 295, 247],
       [  2, 211, 241, 324, 438],
       [  3, 192, 278, 339, 383],
       [  4, 187, 364, 353, 502],
       [  5, 219, 427, 324, 561],
       [  6, 228, 552, 325, 718]])

array([[  1, 237, 176, 295, 247],
       [  2, 211, 241, 324, 438],
       [  3, 192, 278, 339, 383],
       [  4, 187, 364, 353, 502],
       [  5, 219, 427, 324, 561],
       [  6, 228, 552, 325, 718]])

In [4]:
import config
crop_bounds = config.CROP_BOUNDS
crop_bounds
(hmin, hmax), (wmin, wmax) = crop_bounds

((160, 672), (14, 526))

In [5]:
xs = rois[:, (1,2)]
xs
xs = np.clip(xs, wmin, wmax-1)
xs


array([[237, 176],
       [211, 241],
       [192, 278],
       [187, 364],
       [219, 427],
       [228, 552]])

array([[237, 176],
       [211, 241],
       [192, 278],
       [187, 364],
       [219, 427],
       [228, 525]])

In [14]:
ys = rois[:, (3, 4)]
ys
ys = np.clip(ys, hmin, hmax-1)
ys
ys - ys.min(axis=0)

array([[295, 247],
       [324, 438],
       [339, 383],
       [353, 502],
       [324, 561],
       [325, 718]])

array([[295, 247],
       [324, 438],
       [339, 383],
       [353, 502],
       [324, 561],
       [325, 671]])

array([[  0,   0],
       [ 29, 191],
       [ 44, 136],
       [ 58, 255],
       [ 29, 314],
       [ 30, 424]])

In [8]:
returned = np.stack((rois[:, 0], xs[:, 0], ys[:, 0], xs[:, 1], ys[:, 1]))
returned.T
out = returned.T.shape

array([[  1, 237, 295, 176, 247],
       [  2, 211, 324, 241, 438],
       [  3, 192, 339, 278, 383],
       [  4, 187, 353, 364, 502],
       [  5, 219, 324, 427, 561],
       [  6, 228, 325, 525, 671]])