In [1]:
# Show all Jupyter output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# import files from above
import sys
sys.path.append('..')

In [2]:
from src.datasets import TextureDataset
import config

In [3]:
root = "/home/espina/Development/outfit-transfer/data/tina"
texture_path = root + "/texture"
cloth_path = root + "/clothing"
body_path = root + "/body"
roi_path = root + "/rois"

In [4]:
ds = TextureDataset(texture_path, roi_path, cloth_path, crop_bounds=config.CROP_BOUNDS)

In [5]:
import torch
loader = torch.utils.data.DataLoader(ds)

In [6]:
i = iter(loader)

In [27]:
tex, roi, clo, tar = next(i)
tex = tex.cuda()
roi = roi.cuda()
clo = clo.cuda()
tar = tar.cuda()
tex.shape
roi.shape
clo.shape
tar.shape
roi.dtype

torch.Size([1, 3, 512, 512])

torch.Size([1, 6, 5])

torch.Size([1, 3, 512, 512])

torch.Size([1, 3, 512, 512])

torch.float32

In [28]:
roi.max()
roi.min()

tensor(333., device='cuda:0')

tensor(0., device='cuda:0')

In [29]:
roi

tensor([[[  1.,  47.,   0.,   0.,   0.],
         [  2.,  36.,  12.,  71., 166.],
         [  3.,   0.,  57.,  89.,  73.],
         [  4.,  11.,  59., 151., 125.],
         [  5.,  32.,  13., 238., 280.],
         [  6.,  33.,   7., 271., 333.]]], device='cuda:0')

In [30]:
roi.shape
roi_from_2 = roi[:, 1:, :]
roi_from_2

torch.Size([1, 6, 5])

tensor([[[  2.,  36.,  12.,  71., 166.],
         [  3.,   0.,  57.,  89.,  73.],
         [  4.,  11.,  59., 151., 125.],
         [  5.,  32.,  13., 238., 280.],
         [  6.,  33.,   7., 271., 333.]]], device='cuda:0')

In [31]:
from maskrcnn_benchmark.layers import ROIAlign

In [32]:
roi_align = ROIAlign(
    output_size=(128, 128), spatial_scale=1, sampling_ratio=1
)
out = roi_align(tex, roi)
out
out.shape
out.max()
out.min()

tensor([[[[1.6255e-43, 3.2650e-43, 4.8905e-43,  ..., 2.0533e-41,
           2.0697e-41, 2.0858e-41],
          [3.2650e-43, 4.8765e-43, 6.4880e-43,  ..., 2.0536e-41,
           2.0699e-41, 2.0860e-41],
          [4.8905e-43, 6.4880e-43, 8.0995e-43,  ..., 2.0540e-41,
           2.0699e-41, 2.0861e-41],
          ...,
          [8.2270e-42, 8.2284e-42, 8.2298e-42,  ..., 8.3798e-42,
           8.3812e-42, 8.3826e-42],
          [8.2284e-42, 8.2312e-42, 8.2326e-42,  ..., 8.3812e-42,
           8.3840e-42, 8.3868e-42],
          [8.2326e-42, 8.2340e-42, 8.2340e-42,  ..., 8.3854e-42,
           8.3882e-42, 8.3882e-42]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

torch.Size([1, 3, 128, 128])

tensor(2.0896e-41, device='cuda:0')

tensor(0., device='cuda:0')

torch.Size([1, 3, 128, 128])

tensor(2.0942e-41, device='cuda:0')

tensor(0., device='cuda:0')

In [21]:
from maskrcnn_benchmark.layers import ROIPool
roi_pool = ROIPool((128,128), 1)
# ROI POOL is GPU only
out = roi_pool(tex, roi)
out
out.shape
out.max()
out.min()

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [2.0941e-41, 2.0941e-41, 2.0941e-41,  ..., 2.0941e-41,
           2.0941e-41, 2.0941e-41],
          [2.0941e-41, 2.0941e-41, 2.0941e-41,  ..., 2.0941e-41,
           2.0941e-41, 2.0941e-41],
          [2.0941e-41, 2.0941e-41, 2.0941e-41,  ..., 2.0941e-41,
           2.0941e-41, 2.0941e-41]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

torch.Size([1, 3, 128, 128])

tensor(2.0941e-41, device='cuda:0')

tensor(0., device='cuda:0')