In [1]:
# Show all Jupyter output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import torch
from torch import nn
from torchvision import models

import sys
sys.path.append('..')

In [2]:
from src.datasets import TextureDataset

from src.datasets import TextureDataset

texture_dir = "../data/andrew/texture"
cloth_dir = "../data/andrew/clothing"
rois_db = "../data/andrew/rois.csv"


CROP_BOUNDS = (
    (160, 672),  # HEIGHT (determined by looking at sample frames. want to get the head)
    (14, 526),  # WIDTH (calculated by (540 - 512)/2, then centered  )
)

texture_dataset = TextureDataset(
    texture_dir, rois_db, cloth_dir, crop_bounds=CROP_BOUNDS
)

In [3]:
from torch.utils.data import DataLoader

loader = DataLoader(texture_dataset, batch_size=2)

In [4]:
iterator = iter(loader)

In [7]:
x = next(iterator)

In [6]:
import torch
import sys
sys.path.append("/home/remoteuser/faster-rcnn.pytorch/lib")
from model.roi_layers import ROIAlign
from torch import nn

from src.nets import UNetDown, UNetUp

NUM_ROI = 6

In [9]:
roi_align = ROIAlign((128, 128), 1, 1)

In [8]:
rois = x[1].view(-1,5)

In [10]:
rois
rois.shape

tensor([[  2.,  44.,  16.,   0.,   0.],
        [  2.,  39.,  32.,  67., 249.],
        [  2.,  76.,  36., 107., 155.],
        [  2.,  55.,   0., 263., 295.],
        [  2.,  31.,  39., 316., 389.],
        [  2.,   0.,  93., 375., 444.],
        [  3., 119.,  73.,   0.,   0.],
        [  3., 127., 182.,  96., 380.],
        [  3.,  55., 174., 162., 260.],
        [  3.,   9.,   0., 378., 494.],
        [  3.,   0., 160., 481., 494.],
        [  3.,   1., 142., 487., 494.]])

torch.Size([12, 5])

In [ ]:
out = roi_align(x[0], rois=rois)
out.shape
out

In [11]:
rois[:, 0]

tensor([2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3.])

In [12]:
rois[0,0]

tensor(2.)

In [13]:
rois[:, 0] = rois[:,0] - rois[0,0]   # KEY COMPONENT: RESET THE IMAGE IDS PER BATCH SIZE
rois

tensor([[  0.,  44.,  16.,   0.,   0.],
        [  0.,  39.,  32.,  67., 249.],
        [  0.,  76.,  36., 107., 155.],
        [  0.,  55.,   0., 263., 295.],
        [  0.,  31.,  39., 316., 389.],
        [  0.,   0.,  93., 375., 444.],
        [  1., 119.,  73.,   0.,   0.],
        [  1., 127., 182.,  96., 380.],
        [  1.,  55., 174., 162., 260.],
        [  1.,   9.,   0., 378., 494.],
        [  1.,   0., 160., 481., 494.],
        [  1.,   1., 142., 487., 494.]])

In [14]:
out = roi_align(x[0], rois=rois)
out.shape
out

torch.Size([12, 3, 128, 128])

tensor([[[[0.1020, 0.1020, 0.1020,  ..., 0.1020, 0.1020, 0.1020],
          [0.1020, 0.1020, 0.1020,  ..., 0.1020, 0.1020, 0.1020],
          [0.1020, 0.1020, 0.1020,  ..., 0.1020, 0.1020, 0.1020],
          ...,
          [0.1020, 0.1020, 0.1020,  ..., 0.1020, 0.1020, 0.1020],
          [0.1020, 0.1020, 0.1020,  ..., 0.1020, 0.1020, 0.1020],
          [0.1020, 0.1020, 0.1020,  ..., 0.1020, 0.1020, 0.1020]],

         [[0.1098, 0.1098, 0.1098,  ..., 0.1098, 0.1098, 0.1098],
          [0.1098, 0.1098, 0.1098,  ..., 0.1098, 0.1098, 0.1098],
          [0.1098, 0.1098, 0.1098,  ..., 0.1098, 0.1098, 0.1098],
          ...,
          [0.1098, 0.1098, 0.1098,  ..., 0.1098, 0.1098, 0.1098],
          [0.1098, 0.1098, 0.1098,  ..., 0.1098, 0.1098, 0.1098],
          [0.1098, 0.1098, 0.1098,  ..., 0.1098, 0.1098, 0.1098]],

         [[0.0980, 0.0980, 0.0980,  ..., 0.0980, 0.0980, 0.0980],
          [0.0980, 0.0980, 0.0980,  ..., 0.0980, 0.0980, 0.0980],
          [0.0980, 0.0980, 0.0980,  ..., 0